version: '3.8'

services:
  docker:
    container_name: docker-inside
    image: docker
    restart: always
    stdin_open: true
    tty: true        
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-server
    privileged: true
    hostname: jenkinsserver
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      jenkins-net:
        aliases:
          -jenkins-net
    volumes:
      -jenkins-home:/var/jenkins_home
volumes:
  jenkins-data:
  
networks:
  jenkins-net:
