version: '3.8'


services:
  dind:
    image: docker:dind
    privileged: true
    user: root
    container_name: dind
    restart: unless-stopped
    networks:
      jenkins:
        aliases:
          - docker
    expose:
      - "2376"
    volumes:
      - docker-certs-ca:/certs/ca
      - docker-certs-client:/certs/client
      - jenkins-data:/var/jenkins_home
    environment:
      - DOCKER_TLS_CERTDIR=/certs

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    user: root
    restart: unless-stopped
    ports:      
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    networks:
      - jenkins
    depends_on:
      - dind
    volumes:
      - docker-certs-client:/certs/client:ro
      - jenkins-data:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker:Z
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
      
volumes:
  jenkins-data:
  docker-certs-ca:
  docker-certs-client:


networks:
  jenkins:
    driver: bridge
