version: '3.8'

services:
  docker:
    container_name: docker-inside
    image: docker
    restart: always
    stdin_open: true
    tty: true        
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1

